// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HomePlacementConfig {
    /**
     * Creates a new HomePlacementConfig instance.
     * @param {Partial<HomePlacementConfig>} [$$source = {}] - The source object to create the HomePlacementConfig.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("subtitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subtitle"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HomePlacementConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HomePlacementConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HomePlacementConfig(/** @type {Partial<HomePlacementConfig>} */($$parsedSource));
    }
}

export class Runtime {
    /**
     * Creates a new Runtime instance.
     * @param {Partial<Runtime>} [$$source = {}] - The source object to create the Runtime.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("packageHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["packageHash"] = "";
        }
        if (!("assetBaseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["assetBaseURL"] = "";
        }
        if (!("indexURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["indexURL"] = "";
        }
        if (!("window" in $$source)) {
            /**
             * @member
             * @type {WindowConfig}
             */
            this["window"] = (new WindowConfig());
        }
        if (!("home" in $$source)) {
            /**
             * @member
             * @type {HomePlacementConfig}
             */
            this["home"] = (new HomePlacementConfig());
        }
        if (!("slots" in $$source)) {
            /**
             * @member
             * @type {SlotRuntime[]}
             */
            this["slots"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Runtime instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Runtime}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField5_0($$parsedSource["window"]);
        }
        if ("home" in $$parsedSource) {
            $$parsedSource["home"] = $$createField6_0($$parsedSource["home"]);
        }
        if ("slots" in $$parsedSource) {
            $$parsedSource["slots"] = $$createField7_0($$parsedSource["slots"]);
        }
        return new Runtime(/** @type {Partial<Runtime>} */($$parsedSource));
    }
}

export class SlotRuntime {
    /**
     * Creates a new SlotRuntime instance.
     * @param {Partial<SlotRuntime>} [$$source = {}] - The source object to create the SlotRuntime.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("packageHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["packageHash"] = "";
        }
        if (!("assetBaseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["assetBaseURL"] = "";
        }
        if (!("indexURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["indexURL"] = "";
        }
        if (!("window" in $$source)) {
            /**
             * @member
             * @type {WindowConfig}
             */
            this["window"] = (new WindowConfig());
        }
        if (!("home" in $$source)) {
            /**
             * @member
             * @type {HomePlacementConfig}
             */
            this["home"] = (new HomePlacementConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SlotRuntime instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SlotRuntime}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField6_0($$parsedSource["window"]);
        }
        if ("home" in $$parsedSource) {
            $$parsedSource["home"] = $$createField7_0($$parsedSource["home"]);
        }
        return new SlotRuntime(/** @type {Partial<SlotRuntime>} */($$parsedSource));
    }
}

export class WindowConfig {
    /**
     * Creates a new WindowConfig instance.
     * @param {Partial<WindowConfig>} [$$source = {}] - The source object to create the WindowConfig.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowConfig(/** @type {Partial<WindowConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = WindowConfig.createFrom;
const $$createType1 = HomePlacementConfig.createFrom;
const $$createType2 = SlotRuntime.createFrom;
const $$createType3 = $Create.Array($$createType2);
