// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as ads$0 from "../../../../../cursor/internal/ads/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as config$0 from "../../../../../cursor/internal/backend/server/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as bridge$0 from "../../../../../cursor/internal/bridge/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as client$0 from "../../../../../cursor/internal/client/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as updater$0 from "../../../../../cursor/internal/updater/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "ad:updated": bridge$0.AdRuntime;
            "model-adapter-test:updated": bridge$0.ModelAdapterTestResultsPayload;
            "proxy:state": bridge$0.ProxyState;
            "update:error": updater$0.ErrorPayload;
            "update:progress": updater$0.ProgressPayload;
            "update:ready": updater$0.ReadyPayload;
            "update:state": updater$0.StatePayload;
            "user-config:changed": bridge$0.UserConfig;
        }
    }
}
