//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ads$0 from "../../../../../cursor/internal/ads/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../../../../cursor/internal/backend/server/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bridge$0 from "../../../../../cursor/internal/bridge/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "../../../../../cursor/internal/client/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../../../../../cursor/internal/updater/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "ad:updated": $$createType0,
        "model-adapter-test:updated": $$createType1,
        "proxy:state": $$createType2,
        "update:error": $$createType3,
        "update:progress": $$createType4,
        "update:ready": $$createType5,
        "update:state": $$createType6,
        "user-config:changed": $$createType7,
    }));
}

// Private type creation functions
const $$createType0 = ads$0.Runtime.createFrom;
const $$createType1 = client$0.ModelAdapterTestResultsPayload.createFrom;
const $$createType2 = client$0.ProxyState.createFrom;
const $$createType3 = updater$0.ErrorPayload.createFrom;
const $$createType4 = updater$0.ProgressPayload.createFrom;
const $$createType5 = updater$0.ReadyPayload.createFrom;
const $$createType6 = updater$0.StatePayload.createFrom;
const $$createType7 = config$0.Config.createFrom;

configure();
