// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../backend/server/config/models.js";

/**
 * LicenseAPIResult 定义了当前模块中的 LicenseAPIResult 类型。
 * @typedef {any} LicenseAPIResult
 */

/**
 * LicenseActionRequest 定义了当前模块中的 LicenseActionRequest 类型。
 */
export class LicenseActionRequest {
    /**
     * Creates a new LicenseActionRequest instance.
     * @param {Partial<LicenseActionRequest>} [$$source = {}] - The source object to create the LicenseActionRequest.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * Host 表示当前声明中的 Host。
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("code" in $$source)) {
            /**
             * Code 表示当前声明中的 Code。
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("deviceId" in $$source)) {
            /**
             * DeviceID 表示当前声明中的 DeviceID。
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("deviceMeta" in $$source)) {
            /**
             * DeviceMeta 表示当前声明中的 DeviceMeta。
             * @member
             * @type {string}
             */
            this["deviceMeta"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LicenseActionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LicenseActionRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LicenseActionRequest(/** @type {Partial<LicenseActionRequest>} */($$parsedSource));
    }
}

/**
 * LicenseSwitchDeviceRequest 定义了当前模块中的 LicenseSwitchDeviceRequest 类型。
 */
export class LicenseSwitchDeviceRequest {
    /**
     * Creates a new LicenseSwitchDeviceRequest instance.
     * @param {Partial<LicenseSwitchDeviceRequest>} [$$source = {}] - The source object to create the LicenseSwitchDeviceRequest.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * Host 表示当前声明中的 Host。
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("code" in $$source)) {
            /**
             * Code 表示当前声明中的 Code。
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("fromDeviceId" in $$source)) {
            /**
             * FromDeviceID 表示当前声明中的 FromDeviceID。
             * @member
             * @type {string}
             */
            this["fromDeviceId"] = "";
        }
        if (!("toDeviceId" in $$source)) {
            /**
             * ToDeviceID 表示当前声明中的 ToDeviceID。
             * @member
             * @type {string}
             */
            this["toDeviceId"] = "";
        }
        if (!("remark" in $$source)) {
            /**
             * Remark 表示当前声明中的 Remark。
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LicenseSwitchDeviceRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LicenseSwitchDeviceRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LicenseSwitchDeviceRequest(/** @type {Partial<LicenseSwitchDeviceRequest>} */($$parsedSource));
    }
}

/**
 * ModelAdapterTestResult 表示一次模型测速结果。
 */
export class ModelAdapterTestResult {
    /**
     * Creates a new ModelAdapterTestResult instance.
     * @param {Partial<ModelAdapterTestResult>} [$$source = {}] - The source object to create the ModelAdapterTestResult.
     */
    constructor($$source = {}) {
        if (!("adapterID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["adapterID"] = "";
        }
        if (!("requestHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestHash"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("tokensPerSecond" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tokensPerSecond"] = 0;
        }
        if (!("firstTextTokenMS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["firstTextTokenMS"] = 0;
        }
        if (!("totalDurationMS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalDurationMS"] = 0;
        }
        if (!("outputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outputTokens"] = 0;
        }
        if (!("tokensEstimated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tokensEstimated"] = false;
        }
        if (!("summaryText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summaryText"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("rawResponse" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rawResponse"] = "";
        }
        if (!("testedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["testedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelAdapterTestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelAdapterTestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelAdapterTestResult(/** @type {Partial<ModelAdapterTestResult>} */($$parsedSource));
    }
}

/**
 * ModelAdapterTestResultsPayload 用于向前端广播当前测速结果快照。
 */
export class ModelAdapterTestResultsPayload {
    /**
     * Creates a new ModelAdapterTestResultsPayload instance.
     * @param {Partial<ModelAdapterTestResultsPayload>} [$$source = {}] - The source object to create the ModelAdapterTestResultsPayload.
     */
    constructor($$source = {}) {
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {ModelAdapterTestResult[]}
             */
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelAdapterTestResultsPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelAdapterTestResultsPayload}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new ModelAdapterTestResultsPayload(/** @type {Partial<ModelAdapterTestResultsPayload>} */($$parsedSource));
    }
}

export class ModelListRequest {
    /**
     * Creates a new ModelListRequest instance.
     * @param {Partial<ModelListRequest>} [$$source = {}] - The source object to create the ModelListRequest.
     */
    constructor($$source = {}) {
        if (!("baseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseURL"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelListRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelListRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelListRequest(/** @type {Partial<ModelListRequest>} */($$parsedSource));
    }
}

/**
 * ProxyState 定义了当前模块中的 ProxyState 类型。
 */
export class ProxyState {
    /**
     * Creates a new ProxyState instance.
     * @param {Partial<ProxyState>} [$$source = {}] - The source object to create the ProxyState.
     */
    constructor($$source = {}) {
        if (!("listenAddr" in $$source)) {
            /**
             * ListenAddr 保留旧字段兼容前端缓存，实际值等于 proxyListenAddr。
             * @member
             * @type {string}
             */
            this["listenAddr"] = "";
        }
        if (!("running" in $$source)) {
            /**
             * Running 保留旧字段兼容前端缓存，实际值等于 proxyRunning。
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("backendListenAddr" in $$source)) {
            /**
             * BackendListenAddr 表示嵌入式 backend 监听地址。
             * @member
             * @type {string}
             */
            this["backendListenAddr"] = "";
        }
        if (!("backendRunning" in $$source)) {
            /**
             * BackendRunning 表示嵌入式 backend 是否已启动。
             * @member
             * @type {boolean}
             */
            this["backendRunning"] = false;
        }
        if (!("proxyListenAddr" in $$source)) {
            /**
             * ProxyListenAddr 表示 MITM 代理监听地址。
             * @member
             * @type {string}
             */
            this["proxyListenAddr"] = "";
        }
        if (!("proxyRunning" in $$source)) {
            /**
             * ProxyRunning 表示 MITM 代理是否已启动。
             * @member
             * @type {boolean}
             */
            this["proxyRunning"] = false;
        }
        if (!("cursorSettingsApplied" in $$source)) {
            /**
             * CursorSettingsApplied 表示宿主代理设置是否已注入。
             * @member
             * @type {boolean}
             */
            this["cursorSettingsApplied"] = false;
        }
        if (!("netProxySource" in $$source)) {
            /**
             * NetProxySource 表示当前出站网络代理来源：system/env/direct。
             * @member
             * @type {string}
             */
            this["netProxySource"] = "";
        }
        if (!("netProxyActive" in $$source)) {
            /**
             * NetProxyActive 表示当前出站网络代理是否启用。
             * @member
             * @type {boolean}
             */
            this["netProxyActive"] = false;
        }
        if (!("netProxyUsingSystem" in $$source)) {
            /**
             * NetProxyUsingSystem 表示当前出站网络代理是否来自操作系统代理。
             * @member
             * @type {boolean}
             */
            this["netProxyUsingSystem"] = false;
        }
        if (!("netProxyUsingEnv" in $$source)) {
            /**
             * NetProxyUsingEnv 表示当前出站网络代理是否来自环境变量。
             * @member
             * @type {boolean}
             */
            this["netProxyUsingEnv"] = false;
        }
        if (!("netProxyHttp" in $$source)) {
            /**
             * NetProxyHTTP 表示当前 HTTP 代理地址，已移除凭据。
             * @member
             * @type {string}
             */
            this["netProxyHttp"] = "";
        }
        if (!("netProxyHttps" in $$source)) {
            /**
             * NetProxyHTTPS 表示当前 HTTPS 代理地址，已移除凭据。
             * @member
             * @type {string}
             */
            this["netProxyHttps"] = "";
        }
        if (!("netProxyPacIgnored" in $$source)) {
            /**
             * NetProxyPACIgnored 表示检测到 PAC/自动代理但本轮按直连处理。
             * @member
             * @type {boolean}
             */
            this["netProxyPacIgnored"] = false;
        }
        if (!("netProxyDescription" in $$source)) {
            /**
             * NetProxyDescription 表示当前出站网络代理摘要，已移除凭据。
             * @member
             * @type {string}
             */
            this["netProxyDescription"] = "";
        }
        if (!("lastError" in $$source)) {
            /**
             * LastError 表示当前声明中的 LastError。
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyState(/** @type {Partial<ProxyState>} */($$parsedSource));
    }
}

/**
 * UsageRecord 定义了当前模块中的 UsageRecord 类型。
 */
export class UsageRecord {
    /**
     * Creates a new UsageRecord instance.
     * @param {Partial<UsageRecord>} [$$source = {}] - The source object to create the UsageRecord.
     */
    constructor($$source = {}) {
        if (!("createdAt" in $$source)) {
            /**
             * CreatedAt 表示当前声明中的 CreatedAt。
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("runtimeModelId" in $$source)) {
            /**
             * RuntimeModelID 表示当前声明中的 RuntimeModelID。
             * @member
             * @type {string}
             */
            this["runtimeModelId"] = "";
        }
        if (!("requestId" in $$source)) {
            /**
             * RequestID 表示当前声明中的 RequestID。
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("conversationId" in $$source)) {
            /**
             * ConversationID 表示当前声明中的 ConversationID。
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageRecord(/** @type {Partial<UsageRecord>} */($$parsedSource));
    }
}

/**
 * UsageRecordsData 定义了当前模块中的 UsageRecordsData 类型。
 */
export class UsageRecordsData {
    /**
     * Creates a new UsageRecordsData instance.
     * @param {Partial<UsageRecordsData>} [$$source = {}] - The source object to create the UsageRecordsData.
     */
    constructor($$source = {}) {
        if (!("items" in $$source)) {
            /**
             * Items 表示当前声明中的 Items。
             * @member
             * @type {UsageRecord[]}
             */
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * Total 表示当前声明中的 Total。
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * Page 表示当前声明中的 Page。
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * PageSize 表示当前声明中的 PageSize。
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageRecordsData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageRecordsData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new UsageRecordsData(/** @type {Partial<UsageRecordsData>} */($$parsedSource));
    }
}

/**
 * UsageRecordsRequest 定义了当前模块中的 UsageRecordsRequest 类型。
 */
export class UsageRecordsRequest {
    /**
     * Creates a new UsageRecordsRequest instance.
     * @param {Partial<UsageRecordsRequest>} [$$source = {}] - The source object to create the UsageRecordsRequest.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * Host 表示当前声明中的 Host。
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("code" in $$source)) {
            /**
             * Code 表示当前声明中的 Code。
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * Page 表示当前声明中的 Page。
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * PageSize 表示当前声明中的 PageSize。
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }
        if (!("startTime" in $$source)) {
            /**
             * StartTime 表示当前声明中的 StartTime。
             * @member
             * @type {string}
             */
            this["startTime"] = "";
        }
        if (!("endTime" in $$source)) {
            /**
             * EndTime 表示当前声明中的 EndTime。
             * @member
             * @type {string}
             */
            this["endTime"] = "";
        }
        if (!("requestId" in $$source)) {
            /**
             * RequestID 表示当前声明中的 RequestID。
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("conversationId" in $$source)) {
            /**
             * ConversationID 表示当前声明中的 ConversationID。
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("runtimeModelId" in $$source)) {
            /**
             * RuntimeModelID 表示当前声明中的 RuntimeModelID。
             * @member
             * @type {string}
             */
            this["runtimeModelId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageRecordsRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageRecordsRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageRecordsRequest(/** @type {Partial<UsageRecordsRequest>} */($$parsedSource));
    }
}

/**
 * UsageRecordsResult 定义了当前模块中的 UsageRecordsResult 类型。
 */
export class UsageRecordsResult {
    /**
     * Creates a new UsageRecordsResult instance.
     * @param {Partial<UsageRecordsResult>} [$$source = {}] - The source object to create the UsageRecordsResult.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * Code 表示当前声明中的 Code。
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * Message 表示当前声明中的 Message。
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * Data 表示当前声明中的 Data。
             * @member
             * @type {UsageRecordsData}
             */
            this["data"] = (new UsageRecordsData());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageRecordsResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageRecordsResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new UsageRecordsResult(/** @type {Partial<UsageRecordsResult>} */($$parsedSource));
    }
}

/**
 * UserConfig 定义了当前模块中的 UserConfig 类型。
 */
export const UserConfig = config$0.Config;

/**
 * UserConfig 定义了当前模块中的 UserConfig 类型。
 * @typedef {config$0.Config} UserConfig
 */

// Private type creation functions
const $$createType0 = ModelAdapterTestResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = UsageRecord.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = UsageRecordsData.createFrom;
