// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("log" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["log"] = false;
        }
        if (!("providerStreamIdleTimeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["providerStreamIdleTimeout"] = 0;
        }
        if (!("backendListenAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backendListenAddr"] = "";
        }
        if (!("proxyListenAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyListenAddr"] = "";
        }
        if (!("modelAdapters" in $$source)) {
            /**
             * @member
             * @type {ModelAdapterConfig[]}
             */
            this["modelAdapters"] = [];
        }
        if (!("routing" in $$source)) {
            /**
             * @member
             * @type {RoutingConfig}
             */
            this["routing"] = (new RoutingConfig());
        }
        if (!("homeMetrics" in $$source)) {
            /**
             * @member
             * @type {HomeMetricsConfig}
             */
            this["homeMetrics"] = (new HomeMetricsConfig());
        }
        if (!("lastAgentModelHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastAgentModelHash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modelAdapters" in $$parsedSource) {
            $$parsedSource["modelAdapters"] = $$createField4_0($$parsedSource["modelAdapters"]);
        }
        if ("routing" in $$parsedSource) {
            $$parsedSource["routing"] = $$createField5_0($$parsedSource["routing"]);
        }
        if ("homeMetrics" in $$parsedSource) {
            $$parsedSource["homeMetrics"] = $$createField6_0($$parsedSource["homeMetrics"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class HomeMetricsConfig {
    /**
     * Creates a new HomeMetricsConfig instance.
     * @param {Partial<HomeMetricsConfig>} [$$source = {}] - The source object to create the HomeMetricsConfig.
     */
    constructor($$source = {}) {
        if (!("includeCacheWriteInHitRate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["includeCacheWriteInHitRate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HomeMetricsConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HomeMetricsConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HomeMetricsConfig(/** @type {Partial<HomeMetricsConfig>} */($$parsedSource));
    }
}

export class ModelAdapterConfig {
    /**
     * Creates a new ModelAdapterConfig instance.
     * @param {Partial<ModelAdapterConfig>} [$$source = {}] - The source object to create the ModelAdapterConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("baseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseURL"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("tooltipData" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tooltipData"] = "";
        }
        if (!("modelID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelID"] = "";
        }
        if (!("reasoningEffort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reasoningEffort"] = "";
        }
        if (!("openAIEndpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["openAIEndpoint"] = "";
        }
        if (!("openAIExtraParamsEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["openAIExtraParamsEnabled"] = false;
        }
        if (!("openAIExtraParamsJSON" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["openAIExtraParamsJSON"] = "";
        }
        if (!("customHeadersEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["customHeadersEnabled"] = false;
        }
        if (!("customHeadersJSON" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["customHeadersJSON"] = "";
        }
        if (!("anthropicExtraParamsEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["anthropicExtraParamsEnabled"] = false;
        }
        if (!("anthropicExtraParamsJSON" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["anthropicExtraParamsJSON"] = "";
        }
        if (!("contextWindowTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["contextWindowTokens"] = 0;
        }
        if (!("maxCompletionTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxCompletionTokens"] = 0;
        }
        if (!("anthropicMaxTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["anthropicMaxTokens"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["anthropicThinkingEffort"] = undefined;
        }
        if (!("thinkingBudgetTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["thinkingBudgetTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelAdapterConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelAdapterConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelAdapterConfig(/** @type {Partial<ModelAdapterConfig>} */($$parsedSource));
    }
}

export class RoutingConfig {
    /**
     * Creates a new RoutingConfig instance.
     * @param {Partial<RoutingConfig>} [$$source = {}] - The source object to create the RoutingConfig.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoutingConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RoutingConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoutingConfig(/** @type {Partial<RoutingConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ModelAdapterConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = RoutingConfig.createFrom;
const $$createType3 = HomeMetricsConfig.createFrom;
