// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ads$0 from "../ads/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.AdRuntime>}
 */
export function GetAdRuntime() {
    return $Call.ByID(3960994066).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<void>}
 */
export function OpenExternalURL(rawURL) {
    return $Call.ByID(1734665791, rawURL);
}

// Private type creation functions
const $$createType0 = ads$0.Runtime.createFrom;
