// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as AdService from "./adservice.js";
import * as MetricsService from "./metricsservice.js";
import * as ProxyService from "./proxyservice.js";
import * as WindowService from "./windowservice.js";
export {
    AdService,
    MetricsService,
    ProxyService,
    WindowService
};

export {
    AdRuntime,
    FooterAuthorInfo,
    HomeMetricsSummary,
    LicenseActionRequest,
    LicenseSwitchDeviceRequest,
    ModelAdapterConfig,
    ModelAdapterTestResult,
    ModelAdapterTestResultsPayload,
    ModelListRequest,
    ProxyState,
    UsageRecordsRequest,
    UsageRecordsResult,
    UserConfig
} from "./models.js";

import * as $models from "./models.js";

/**
 * LicenseAPIResult 定义了当前模块中的 LicenseAPIResult 类型。
 * @typedef {$models.LicenseAPIResult} LicenseAPIResult
 */
