// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ads$0 from "../ads/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../backend/server/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "../client/models.js";

export const AdRuntime = ads$0.Runtime;

/**
 * @typedef {ads$0.Runtime} AdRuntime
 */

/**
 * FooterAuthorInfo 定义首页底部作者入口的展示信息。
 */
export class FooterAuthorInfo {
    /**
     * Creates a new FooterAuthorInfo instance.
     * @param {Partial<FooterAuthorInfo>} [$$source = {}] - The source object to create the FooterAuthorInfo.
     */
    constructor($$source = {}) {
        if (!("buttonText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buttonText"] = "";
        }
        if (!("dialogTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dialogTitle"] = "";
        }
        if (!("dialogContent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dialogContent"] = "";
        }
        if (!("dialogConfirmText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dialogConfirmText"] = "";
        }
        if (!("dialogCancelText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dialogCancelText"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FooterAuthorInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FooterAuthorInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FooterAuthorInfo(/** @type {Partial<FooterAuthorInfo>} */($$parsedSource));
    }
}

/**
 * HomeMetricsSummary 定义首页展示的历史统计摘要。
 */
export class HomeMetricsSummary {
    /**
     * Creates a new HomeMetricsSummary instance.
     * @param {Partial<HomeMetricsSummary>} [$$source = {}] - The source object to create the HomeMetricsSummary.
     */
    constructor($$source = {}) {
        if (!("providerCallsTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["providerCallsTotal"] = 0;
        }
        if (!("turnsTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["turnsTotal"] = 0;
        }
        if (!("validTurnsTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["validTurnsTotal"] = 0;
        }
        if (!("invalidTurnsTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["invalidTurnsTotal"] = 0;
        }
        if (!("requestTokensTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestTokensTotal"] = 0;
        }
        if (!("promptTokensTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["promptTokensTotal"] = 0;
        }
        if (!("cacheReadTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cacheReadTokens"] = 0;
        }
        if (!("cacheWriteTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cacheWriteTokens"] = 0;
        }
        if (!("cacheHitRate" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["cacheHitRate"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HomeMetricsSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HomeMetricsSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HomeMetricsSummary(/** @type {Partial<HomeMetricsSummary>} */($$parsedSource));
    }
}

/**
 * LicenseAPIResult 定义了当前模块中的 LicenseAPIResult 类型。
 * @typedef {client$0.LicenseAPIResult} LicenseAPIResult
 */

/**
 * LicenseActionRequest 定义了当前模块中的 LicenseActionRequest 类型。
 */
export const LicenseActionRequest = client$0.LicenseActionRequest;

/**
 * LicenseActionRequest 定义了当前模块中的 LicenseActionRequest 类型。
 * @typedef {client$0.LicenseActionRequest} LicenseActionRequest
 */

/**
 * LicenseSwitchDeviceRequest 定义了当前模块中的 LicenseSwitchDeviceRequest 类型。
 */
export const LicenseSwitchDeviceRequest = client$0.LicenseSwitchDeviceRequest;

/**
 * LicenseSwitchDeviceRequest 定义了当前模块中的 LicenseSwitchDeviceRequest 类型。
 * @typedef {client$0.LicenseSwitchDeviceRequest} LicenseSwitchDeviceRequest
 */

/**
 * ModelAdapterConfig 定义模型测速使用的模型配置结构。
 */
export const ModelAdapterConfig = config$0.ModelAdapterConfig;

/**
 * ModelAdapterConfig 定义模型测速使用的模型配置结构。
 * @typedef {config$0.ModelAdapterConfig} ModelAdapterConfig
 */

/**
 * ModelAdapterTestResult 定义一次模型测速结果。
 */
export const ModelAdapterTestResult = client$0.ModelAdapterTestResult;

/**
 * ModelAdapterTestResult 定义一次模型测速结果。
 * @typedef {client$0.ModelAdapterTestResult} ModelAdapterTestResult
 */

/**
 * ModelAdapterTestResultsPayload 定义测速结果事件载荷。
 */
export const ModelAdapterTestResultsPayload = client$0.ModelAdapterTestResultsPayload;

/**
 * ModelAdapterTestResultsPayload 定义测速结果事件载荷。
 * @typedef {client$0.ModelAdapterTestResultsPayload} ModelAdapterTestResultsPayload
 */

export const ModelListRequest = client$0.ModelListRequest;

/**
 * @typedef {client$0.ModelListRequest} ModelListRequest
 */

/**
 * Public DTOs remain in package main for Wails service compatibility.
 * ProxyState 定义了当前模块中的 ProxyState 类型。
 */
export const ProxyState = client$0.ProxyState;

/**
 * Public DTOs remain in package main for Wails service compatibility.
 * ProxyState 定义了当前模块中的 ProxyState 类型。
 * @typedef {client$0.ProxyState} ProxyState
 */

/**
 * UsageRecordsRequest 定义了当前模块中的 UsageRecordsRequest 类型。
 */
export const UsageRecordsRequest = client$0.UsageRecordsRequest;

/**
 * UsageRecordsRequest 定义了当前模块中的 UsageRecordsRequest 类型。
 * @typedef {client$0.UsageRecordsRequest} UsageRecordsRequest
 */

/**
 * UsageRecordsResult 定义了当前模块中的 UsageRecordsResult 类型。
 */
export const UsageRecordsResult = client$0.UsageRecordsResult;

/**
 * UsageRecordsResult 定义了当前模块中的 UsageRecordsResult 类型。
 * @typedef {client$0.UsageRecordsResult} UsageRecordsResult
 */

/**
 * UserConfig 定义了当前模块中的 UserConfig 类型。
 */
export const UserConfig = client$0.UserConfig;

/**
 * UserConfig 定义了当前模块中的 UserConfig 类型。
 * @typedef {client$0.UserConfig} UserConfig
 */
