// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService 定义了当前模块中的 ProxyService 类型。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../backend/server/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "../client/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActivateLicense 用于处理与 ActivateLicense 相关的逻辑。
 * @param {$models.LicenseActionRequest} req
 * @returns {$CancellablePromise<$models.LicenseAPIResult>}
 */
export function ActivateLicense(req) {
    return $Call.ByID(2949883810, req);
}

/**
 * ApplyCursorSettings 用于处理与 ApplyCursorSettings 相关的逻辑。
 * @returns {$CancellablePromise<void>}
 */
export function ApplyCursorSettings() {
    return $Call.ByID(1668120069);
}

/**
 * BindLicenseDevice 用于处理与 BindLicenseDevice 相关的逻辑。
 * @param {$models.LicenseActionRequest} req
 * @returns {$CancellablePromise<$models.LicenseAPIResult>}
 */
export function BindLicenseDevice(req) {
    return $Call.ByID(200395426, req);
}

/**
 * ClearCursorSettings 用于处理与 ClearCursorSettings 相关的逻辑。
 * @returns {$CancellablePromise<void>}
 */
export function ClearCursorSettings() {
    return $Call.ByID(222384132);
}

/**
 * ClearLastError 用于处理与 ClearLastError 相关的逻辑。
 * @returns {$CancellablePromise<$models.ProxyState>}
 */
export function ClearLastError() {
    return $Call.ByID(1421069411).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetDeviceID 用于处理与 GetDeviceID 相关的逻辑。
 * @returns {$CancellablePromise<string>}
 */
export function GetDeviceID() {
    return $Call.ByID(810929677);
}

/**
 * GetModelAdapterTestResults 用于处理与 GetModelAdapterTestResults 相关的逻辑。
 * @returns {$CancellablePromise<$models.ModelAdapterTestResult[]>}
 */
export function GetModelAdapterTestResults() {
    return $Call.ByID(3143463064).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetState 用于处理与 GetState 相关的逻辑。
 * @returns {$CancellablePromise<$models.ProxyState>}
 */
export function GetState() {
    return $Call.ByID(683140179).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * IsWindows 用于处理与 IsWindows 相关的逻辑。
 * @returns {$CancellablePromise<boolean>}
 */
export function IsWindows() {
    return $Call.ByID(573621099);
}

/**
 * ListOpenAIModels 自动获取 OpenAI-compatible 模型列表。
 * @param {$models.ModelListRequest} input
 * @returns {$CancellablePromise<string[]>}
 */
export function ListOpenAIModels(input) {
    return $Call.ByID(2509635454, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * LoadUserConfig 用于处理与 LoadUserConfig 相关的逻辑。
 * @returns {$CancellablePromise<$models.UserConfig>}
 */
export function LoadUserConfig() {
    return $Call.ByID(1894232271).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * QueryUsageRecords 用于处理与 QueryUsageRecords 相关的逻辑。
 * @param {$models.UsageRecordsRequest} req
 * @returns {$CancellablePromise<$models.UsageRecordsResult>}
 */
export function QueryUsageRecords(req) {
    return $Call.ByID(3560023217, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SaveUserConfig 用于处理与 SaveUserConfig 相关的逻辑。
 * @param {$models.UserConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveUserConfig(cfg) {
    return $Call.ByID(3824177706, cfg);
}

/**
 * SetBaseURL 用于处理与 SetBaseURL 相关的逻辑。
 * @param {string} baseURL
 * @returns {$CancellablePromise<$models.ProxyState>}
 */
export function SetBaseURL(baseURL) {
    return $Call.ByID(4081451048, baseURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ShutdownForQuit 用于处理与 ShutdownForQuit 相关的逻辑。
 * @returns {$CancellablePromise<void>}
 */
export function ShutdownForQuit() {
    return $Call.ByID(31215812);
}

/**
 * StartProxy 用于处理与 StartProxy 相关的逻辑。
 * @returns {$CancellablePromise<$models.ProxyState>}
 */
export function StartProxy() {
    return $Call.ByID(3163192438).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * StopProxy 用于处理与 StopProxy 相关的逻辑。
 * @returns {$CancellablePromise<$models.ProxyState>}
 */
export function StopProxy() {
    return $Call.ByID(168660758).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SwitchLicenseDevice 用于处理与 SwitchLicenseDevice 相关的逻辑。
 * @param {$models.LicenseSwitchDeviceRequest} req
 * @returns {$CancellablePromise<$models.LicenseAPIResult>}
 */
export function SwitchLicenseDevice(req) {
    return $Call.ByID(1166964611, req);
}

/**
 * TestModelAdapter 用于处理与 TestModelAdapter 相关的逻辑。
 * @param {$models.ModelAdapterConfig} adapter
 * @returns {$CancellablePromise<$models.ModelAdapterTestResult>}
 */
export function TestModelAdapter(adapter) {
    return $Call.ByID(850134374, adapter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = client$0.ProxyState.createFrom;
const $$createType1 = client$0.ModelAdapterTestResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = config$0.Config.createFrom;
const $$createType5 = client$0.UsageRecordsResult.createFrom;
