// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 定义了当前模块中的 WindowService 类型。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates 触发一次手动检查更新。
 * @returns {$CancellablePromise<void>}
 */
export function CheckForUpdates() {
    return $Call.ByID(2300612323);
}

/**
 * GetAppVersion 返回当前应用版本号。
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(3233312005);
}

/**
 * GetFooterAuthorInfo 返回首页底部作者入口的展示信息。
 * @returns {$CancellablePromise<$models.FooterAuthorInfo>}
 */
export function GetFooterAuthorInfo() {
    return $Call.ByID(2996587552).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetModelEditorContext 返回当前编辑器窗口的初始化上下文。
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetModelEditorContext() {
    return $Call.ByID(1051082835).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * InstallReadyUpdate 安装当前已下载完成的更新。
 * @returns {$CancellablePromise<void>}
 */
export function InstallReadyUpdate() {
    return $Call.ByID(269933719);
}

/**
 * OpenConfigWindow 打开本地设置目录。
 * @returns {$CancellablePromise<void>}
 */
export function OpenConfigWindow() {
    return $Call.ByID(2106296590);
}

/**
 * OpenFooterAuthorHome 打开作者主页。
 * @returns {$CancellablePromise<void>}
 */
export function OpenFooterAuthorHome() {
    return $Call.ByID(523066919);
}

/**
 * OpenHistoryWindow 用于处理与 OpenHistoryWindow 相关的逻辑。
 * @returns {$CancellablePromise<void>}
 */
export function OpenHistoryWindow() {
    return $Call.ByID(3003173368);
}

/**
 * OpenModelConfigWindow 打开模型配置独立窗口。如果窗口已存在则聚焦。
 * @returns {$CancellablePromise<void>}
 */
export function OpenModelConfigWindow() {
    return $Call.ByID(594178987);
}

/**
 * OpenModelEditorWindow 打开模型编辑器独立窗口。
 * index < 0 表示新增，>= 0 表示编辑对应索引的适配器。
 * adapterJSON 为编辑器初始数据的 JSON 字符串。
 * @param {number} index
 * @param {string} adapterJSON
 * @returns {$CancellablePromise<void>}
 */
export function OpenModelEditorWindow(index, adapterJSON) {
    return $Call.ByID(1134405752, index, adapterJSON);
}

/**
 * SetApp 用于处理与 SetApp 相关的逻辑。
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1392620719, app);
}

/**
 * SetUpdater 关联更新管理器，供前端手动触发检查更新。
 * @param {updater$0.Manager | null} manager
 * @returns {$CancellablePromise<void>}
 */
export function SetUpdater(manager) {
    return $Call.ByID(715662829, manager);
}

// Private type creation functions
const $$createType0 = $models.FooterAuthorInfo.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
